### ISSUE TITLE
Wrong values for CurrentHeaterCoolerState

### ISSUE THREAD

**Issue by TeunVR** [Rickth64/homebridge-mhacwifi1#4]
The plugin returns TargetHeaterCoolerState-enum also when homekit wants to retrieve the current state.
This is not correct. Homekit expects another enum for the current state: CurrentHeaterCoolerState.
Apple thought it was a good idea to use different values there.
Currently the Home-app shows "Heating" in the small tile when it is in state "Cooling".
If i have time i will push a fix.

TargetHeaterCoolerState:
0 ”Heat or Cool”
1 ”Heat”
2 ”Cool”

CurrentHeaterCoolerState:
0 ”Inactive”
1 ”Idle”
2 ”Heating”
3 ”Cooling”

**Comment by TeunVR** [comment]
Well with the fix it is a bit better. At least COOLING and HEATING are correct.
AUTO however is tricky. My ZSX-W in AUTO mode determines if it should COOL or HEAT when you switch on AUTO.
It is not that he will switch automatically between cooling and heating i think. 
Probably have to take outside temperature into account.

**Comment by Rickth64** [comment]
merged
