### ISSUE TITLE
Question: Is this the AC - WiFi adapter?

### ISSUE THREAD

**Issue by ivan-aleksandrov** [Rickth64/homebridge-mhacwifi1#7]
Hello Rick! Sorry to open issue here but I couldn't find any other way to contact you in GitHub or npmjs.

Is this the module you are working with: https://www.intesis.com/products/cloud-solutions/ac-cloud-control/mitsubishi-heavy-accc-wifi-ac-mh-ac-wfi-1?ordercode=INWFIMHI001I000
I can see it is designed to work with Intesis AC Cloud but couldn't find any specific information about the local REST API you are using. And I wanted to be sure this is the module before purchasing it :) 

Thanks!

**Comment by Rickth64** [comment]
Well, it does look similar, but all I can tell you is mine has model number 'MH-AC-WIFI-1' and that's not what I read on the page you provided (but it is in the URL though...). So, no guarantees.
